CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=2048

CONFIG_SMF=y
CONFIG_EVENTS=y
CONFIG_ADC=y
CONFIG_ADC_EMUL=y

CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_FPU=y
CONFIG_GPIO=y
CONFIG_GPIO_EMUL=y
CONFIG_ZTEST=y